HeartDiseasePrediction/Models/DoctorViewModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HeartDiseasePrediction.Models
{
	public class DoctorViewModel
	{
		public int Id { get; set; }
		[Display(Name = "Address")]
		[Required(ErrorMessage = "Doctor Address Is Required"), MaxLength(250)]
		public string Address { get; set; }
		public bool IsAvailable { get; set; }
		[Display(Name = "Specialization")]
		[Required(ErrorMessage = "Doctor Specialization Is Required")]
		public int SpecializationId { get; set; }
		[ForeignKey(nameof(SpecializationId))]
		public virtual Specialization DoctorSpecialization { get; set; }
		public string UserId { get; set; }
		[ForeignKey(nameof(UserId))]
		public virtual ApplicationUser User { get; set; }
		public virtual ICollection<PrescriptionViewModel> prescriptions { get; set; }
		public DoctorViewModel()
		{
			prescriptions = new Collection<PrescriptionViewModel>();
		}

	}
}

HeartDiseasePrediction/Controllers/DoctorController.cs
using HeartDiseasePrediction.Models;
using HeartDiseasePrediction.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace HeartDiseasePrediction.Controllers
{
	//[Authorize(Roles = "MedicalAnalyst")]
	public class DoctorController : Controller
	{
		private readonly IToastNotification _toastNotification;
		Uri baseAddress = new Uri("https://localhost:44304/api");
		HttpClient _client;
		public DoctorController(IToastNotification toastNotification)
		{
			_toastNotification = toastNotification;
			_client = new HttpClient();
			_client.BaseAddress = baseAddress;
		}
		//get all doctors in list
		public async Task<IActionResult> Index()
		{
			var accessToken = HttpContext.Session.GetString("JWToken");
			var sp = _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
			List<DoctorViewModel> doctorViewModel = new List<DoctorViewModel>();
			HttpResponseMessage response = _client.GetAsync(_client.BaseAddress +
				"/Doctor/").Result;
			if (response.IsSuccessStatusCode)
			{
				string data = await response.Content.ReadAsStringAsync();
				doctorViewModel = JsonConvert.DeserializeObject<List<DoctorViewModel>>(data);
			}
			return View(doctorViewModel);
		}
		[HttpPost]
		public async Task<IActionResult> Index(string search)
		{
			var accessToken = HttpContext.Session.GetString("JWToken");
			_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
			List<DoctorViewModel> doctorViewModel = new List<DoctorViewModel>();
			HttpResponseMessage response = _client.GetAsync(_client.BaseAddress +
				$"/Doctor/Search?search={search}").Result;
			if (response.IsSuccessStatusCode)
			{
				string data = await response.Content.ReadAsStringAsync();
				doctorViewModel = JsonConvert.DeserializeObject<List<DoctorViewModel>>(data);
			}
			return View(doctorViewModel);
		}
		//get doctor details
		public async Task<IActionResult> DoctorDetails(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = await _client.GetAsync(_client.BaseAddress +
					$"/Doctor/GetDoctorById?id={id}");
				if (response.IsSuccessStatusCode)
				{
					string data = response.Content.ReadAsStringAsync().Result;
					var doctor = JsonConvert.DeserializeObject<DoctorVM>(data);
					return View(doctor);
				}
				else
				{
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		[HttpGet]
		public async Task<IActionResult> DoctorProfile()
		{
			return View();
		}

		//Edit details of doctor
		[HttpGet]
		public async Task<IActionResult> EditDoctor(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = await _client.GetAsync(_client.BaseAddress +
					$"/Doctor/GetDoctorById?id={id}");
				if (response.IsSuccessStatusCode)
				{
					string data = response.Content.ReadAsStringAsync().Result;
					var doctor = JsonConvert.DeserializeObject<DoctorVM>(data);
					return View(doctor);
				}
				else
				{
					return RedirectToAction("Index");
				}

			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		[HttpPost]
		public async Task<IActionResult> EditDoctor(int id, DoctorVM model)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				string data = JsonConvert.SerializeObject(model);
				StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
				HttpResponseMessage response = await _client.PutAsync(_client.BaseAddress +
					$"/Doctor/EditDoctor?id={id}", content);
				if (response.IsSuccessStatusCode)
				{
					TempData["successMessage"] = "Doctor Details Updated.";
					_toastNotification.AddSuccessToastMessage("Doctor Updated successfully");
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				_toastNotification.AddErrorToastMessage("Doctor Updated Failed");
				return View();
			}
			return View();
		}

		//Delete docotor 
		public async Task<IActionResult> DeleteDoctor(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress +
					$"/Doctor/{id}").Result;
				if (response.IsSuccessStatusCode)
				{
					TempData["successMessage"] = "Doctor Details Deleted.";
					_toastNotification.AddAlertToastMessage("Doctor Deleted successfully");
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
			return View();
		}
	}
}

HeartDiseasePrediction/Views/Doctor/DoctorDetails.cshtml
@model HeartDiseasePrediction.ViewModel.DoctorVM
@{
    ViewData["Title"] = "Doctors Profile Page";
}
<style type="text/css">
    body {
        margin-top: 20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;
    }

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

    .gutters-sm > .col, .gutters-sm > [class*=col-] {
        padding-right: 8px;
        padding-left: 8px;
    }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }

</style>

<div class="container">
    <div class="main-body">
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Doctor</li>
                <li class="breadcrumb-item">Details</li>
                <li class="breadcrumb-item active" aria-current="page">Doctor Profile</li>
            </ol>
        </nav>
   </div>
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><strong>@Model.FirstName</strong> <strong>@Model.LastName</strong></h4>
                            <p class="text-secondary mb-1">Doctor</p>
                            <p class="text-muted font-size-sm">@Model.Email</p>
                            <a class="btn btn-primary" asp-controller="Doctor" asp-action="EditDoctor" asp-route-id="@Model.Id"><i class="fa fa-pencil-square"></i>  Edit</a>
                            <a class="btn btn-danger" asp-controller="Doctor" asp-action="DeleteDoctor" asp-route-id="@Model.Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.FullName
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Email
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.PhoneNumber
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Birth Date</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.BirthDate
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Age</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Age
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Specialization</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Specialization
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Gender
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Address
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    function ConfirmDelete() {
        document.getElementById("");
        var accept = confirm("Are You Sure to delete this actor?");
        if (accept == false) {
            event.preventDefault();
        }
    }
</script>

HeartDiseasePrediction/Views/Doctor/DoctorProfile.cshtml
@model HeartDiseasePrediction.ViewModel.DoctorVM
@{
    ViewData["Title"] = "Doctors Profile Page";
}
<style type="text/css">
    body {
        margin-top: 20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;
    }

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

        .gutters-sm > .col, .gutters-sm > [class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }

</style>

<div class="container">
    <div class="main-body">
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Doctor</li>
                <li class="breadcrumb-item">Details</li>
                <li class="breadcrumb-item active" aria-current="page">Doctor Profile</li>
            </ol>
        </nav>
    </div>
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><strong>Mohamed</strong> <strong>Ahmed</strong></h4>
                            <p class="text-secondary mb-1">Doctor</p>
                            <p class="text-muted font-size-sm">Mohamed12@gmail.com</p>
                            @*<a class="btn btn-primary" asp-controller="Doctor" asp-action="EditDoctor" asp-route-id="@Model.Id"><i class="fa fa-pencil-square"></i>  Edit</a>
                            <a class="btn btn-danger" asp-controller="Doctor" asp-action="DeleteDoctor" asp-route-id="@Model.Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            Mohamed Ahmed Hassan
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            Mohamed12@gmail.com
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            01023399520
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Birth Date</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            29/2/1984
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Age</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            46
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Specialization</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            Heart
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            Male
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            Cairo
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    function ConfirmDelete() {
        document.getElementById("");
        var accept = confirm("Are You Sure to delete this actor?");
        if (accept == false) {
            event.preventDefault();
        }
    }
</script>

HeartDiseasePrediction/Views/Doctor/EditDoctor.cshtml
@model HeartDiseasePrediction.ViewModel.DoctorVM

@{
    ViewData["Title"] = "Doctors Update Page";
}

<section class="book_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-action="EditDoctor" enctype="multipart/form-data">
                    <h4>
                        Update <span>Doctor</span>
                    </h4>
                    <div class="form-row ">
                        <div class="form-group col-lg-6">
                            <label asp-for="@Model.FullName" class="control-label"></label>
                            <input asp-for="@Model.FullName" type="text" class="form-control" id="inputFullName">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.FirstName" class="control-label"></label>
                            <input asp-for="@Model.FirstName" type="text" class="form-control" id="inputFirstname">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.LastName" class="control-label"></label>
                            <input asp-for="@Model.LastName" type="text" class="form-control" id="inputLastName">
                        </div>
                    </div>
                    <div class="form-row ">
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.PhoneNumber" class="control-label"></label>
                            <input asp-for="@Model.PhoneNumber" type="number" class="form-control" id="inputPhone">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.Address" class="control-label"></label>
                            <input asp-for="@Model.Address" type="text" class="form-control" id="inputAddress">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.Specialization" class="control-label"></label>
                            <input asp-for="@Model.Specialization" type="text" class="form-control" id="inputAddress">
                        </div>
                        @*<div class="form-group col-lg-3" hidden>
                            <label for="inputSpecialization">Specialization</label>
                            <select name="" class="form-control wide" id="inputSpecialization">
                                <option value="NoSelected ">--Please Select Specialization-- </option>
                                <option value="Heart ">Heart </option>
                                <option value="Eyses ">Eyses </option>
                            </select>
                        </div>*@
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.Gender"></label>
                            <select asp-for="@Model.Gender" class="form-control wide" id="inputGender" asp-items="Html.GetEnumSelectList<Gender>()">
                                <option value="NoSelected ">--Please Select Gender-- </option>
                            </select>
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.BirthDate"></label>
                            <input asp-for="@Model.BirthDate" type="datetime" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.Email"></label>
                            <input asp-for="@Model.Email" type="text" class="form-control" id="Email">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="">
                            <div class="form-group col-lg-10">
                                <img id="profilePicture" class="border-info rounded-circle" style="max-width:150px" />
                                <label asp-for="ProfileImg" class="w-100"></label>
                                <input  accept="image/*" asp-for="ImageFile"
                                    onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                                <span asp-validation-for="ImageFile" class="text-danger"></span>
                                @*@if (@Model.ImageFile != null)
                                {
                                    <img id="profilePicture" alt="profile" class="profile-picture" style="height:255px; width:255px; object-fit:cover" src="data:image/*;base64)" />
                                }
                                else
                                {
                                    <img id="profilePicture" alt="profile" class="profile-picture" style="height:255px; width:255px; object-fit:cover" src="~/images/avater.png" />
                                }
                                <div class="custom-file mt-2">
                                    <input type="file"
                                           accept="image/*"
                                           asp-for="ImageFile"
                                           class="" onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                                    <label class="custom-file-label" asp-for="ImageFile"></label>
                                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                                </div>*@
                            </div>
                        </div>
                        <div class="form-group col-lg-4" hidden>
                            <label asp-for="@Model.Id"></label>
                            <input asp-for="@Model.Id" type="text" class="form-control" id="Id">
                        </div>
                    </div>
                    <div class="btn-box">
                        <button type="submit" class="btn ">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
@*@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePictureId');
            output.src = $("#ImageFile").val();
        })

        $("#ImageFile").on("change", function () {
            var output = document.getElementById('ProfilePictureId');
            output.src = $(this).val();
        })
    </script>
}*@
@*@section Scripts{
    <script>
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
    onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])"
}*@

HeartDiseasePrediction/Views/Doctor/Index.cshtml
@model IEnumerable<HeartDiseasePrediction.Models.DoctorViewModel>

@{
	ViewData["Title"] = "Doctors List Page";
}

<div class="container mt-4" style="margin:40px">
	<div class="row">
		<div class="col-md-12 offset-md-0">
			<div class="main-body">
				<nav aria-label="breadcrumb" class="main-breadcrumb ">
					<ol class="breadcrumb">
						<li class="breadcrumb-item">Doctor</li>
						<li class="breadcrumb-item">List</li>
						<li class="breadcrumb-item active" aria-current="page">List of Doctors</li>
					</ol>
				</nav>
			</div>
			<div class="form-inline my-2 my-lg-0 d-flex">
				<a asp-controller="Account" asp-action="RegisterOfDoctor" class="btn btn-success">
					<i class="fa fa-plus-circle"></i> Add New
				</a>
			</div>
			@if (!Model.Any())
			{
				<div class="alert alert-warning" role="alert">
					No Doctors Found
				</div>
			}
			else
			{
				<div class="form-inline my-2 my-lg-0 d-flex" style="padding-left:66%">
					@using (Html.BeginForm("Index", "Doctor", FormMethod.Post))
					{
						@Html.TextBox("search",null,new{@class="form-control",placeholder="Search here...",style="margin:5px 0px 5px 5px"})
						<button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> Search</button>
					}
				</div>
				<table class="table table-hover table-responsive table-striped">
					<thead>
						<tr class="text-center bg-dark text-light">
							@*<th>#</th>*@
							<th>FullName</th>
							<th>Email</th>
							<th>Specialization</th>
							<th>Gender</th>
							<th>Age</th>
							<th>Phone</th>
							<th></th>
							@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
						{
						<th>Action</th>
						}*@

						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr>
								@*<td class="align-middle text-center">
						<img class="rounded-circle" src="@item.ProfileImg" alt="@item.FullName" style="max-width:150px">
						</td>*@
								@*<td class="align-middle text-center">
						@item.Id
						</td>*@
								<td class="align-middle text-center">
									@item.User.FullName
								</td>
								<td class="align-middle text-center">
									@item.User.Email
								</td>
								<td class="align-middle text-center">
									@item.DoctorSpecialization.Name
								</td>
								<td class="align-middle text-center">
									@item.User.Gender
								</td>
								<td class="align-middle text-center">
									@item.User.Age
								</td>
								<td class="align-middle text-center">
									@item.User.PhoneNumber
								</td>
								<td class="align-middle text-center">
									<a class="btn btn-outline-primary" asp-controller="Doctor" asp-action="EditDoctor" asp-route-id="@item.Id"><i class="fa fa-pencil-square"></i> Edit</a> |
									<a class="btn btn-outline-info" asp-controller="Doctor" asp-action="DoctorDetails" asp-route-id="@item.Id"><i class="fa fa-eye"></i> Details</a> |
									<a class="btn btn-outline-danger " asp-controller="Doctor" asp-action="DeleteDoctor" asp-route-id="@item.Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
								</td>
								@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
						{
						<td class="align-middle text-center">
						<a class="btn btn-outline-primary" asp-controller="Doctor" asp-action="Edit" asp-route-id="Id"><i class="fa fa-pencil-square"></i> Edit</a> |
						<a class="btn btn-outline-info" asp-controller="Doctor" asp-action="Details" asp-route-id="Id"><i class="fa fa-eye"></i> Details</a> |
						<a class="btn btn-outline-danger " asp-controller="Doctor" asp-action="Delete" asp-route-id="Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
						</td>
						}*@
							</tr>
						}
					</tbody>
				</table>
			}
		</div>
	</div>
</div>
@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
	<div style="position:fixed; right:25px; bottom:65px;" class="text-white">
		<a asp-controller="Actor" asp-action="Create" class="btn btn-success">
			<i class="bi bi-plus-circle"></i> Add New
		</a>
	</div>
}*@

@*@section scripts{
	<script>
		$(document).ready(function){
			toastr.error("test")
		}
	</script>
}*@

<script>

	function ConfirmDelete() {
		document.getElementById("");
		var accept = confirm("Are You Sure to delete this actor?");
		if (accept == false) {
			event.preventDefault();
		}
	}
</script>