HeartDiseasePrediction/Models/ReciptionistViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace HeartDiseasePrediction.Models
{
	public class ReciptionistViewModel
	{
		public int Id { get; set; }
		public string UserId { get; set; }
		[ForeignKey(nameof(UserId))]
		public virtual ApplicationUser User { get; set; }
	}
}

HeartDiseasePrediction/Controllers/ReciptionistController.cs
using HeartDiseasePrediction.Models;
using HeartDiseasePrediction.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace HeartDiseasePrediction.Controllers
{
	public class ReciptionistController : Controller
	{
		private readonly IToastNotification _toastNotification;
		Uri baseAddress = new Uri("https://localhost:44304/api");
		HttpClient _client;
		public ReciptionistController(IToastNotification toastNotification)
		{
			_toastNotification = toastNotification;
			_client = new HttpClient();
			_client.BaseAddress = baseAddress;
		}
		//get all Reciptionists in list
		public async Task<IActionResult> Index()
		{
			var accessToken = HttpContext.Session.GetString("JWToken");
			_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
			List<ReciptionistViewModel> ReciptionistViewModel = new List<ReciptionistViewModel>();
			HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Reciptionist").Result;
			if (response.IsSuccessStatusCode)
			{
				string data = await response.Content.ReadAsStringAsync();
				ReciptionistViewModel = JsonConvert.DeserializeObject<List<ReciptionistViewModel>>(data);
			}
			return View(ReciptionistViewModel);
		}
		[HttpPost]
		public async Task<IActionResult> Index(string search)
		{
			var accessToken = HttpContext.Session.GetString("JWToken");
			_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
			List<ReciptionistViewModel> ReciptionistViewModel = new List<ReciptionistViewModel>();
			HttpResponseMessage response = _client.GetAsync(_client.BaseAddress +
				$"/Reciptionist/Search?search={search}").Result;
			if (response.IsSuccessStatusCode)
			{
				string data = await response.Content.ReadAsStringAsync();
				ReciptionistViewModel = JsonConvert.DeserializeObject<List<ReciptionistViewModel>>(data);
			}
			return View(ReciptionistViewModel);
		}
		//get Reciptionist details
		public async Task<IActionResult> ReciptionistDetails(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = _client.GetAsync(_client.BaseAddress +
					$"/Reciptionist/GetReciptionistById?id={id}").Result;
				if (response.IsSuccessStatusCode)
				{
					string data = response.Content.ReadAsStringAsync().Result;
					var reciptionist = JsonConvert.DeserializeObject<ReciptionistVM>(data);
					return View(reciptionist);
				}
				else
				{
					return RedirectToAction("ReciptionistDetails");
				}

			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		//Edit details of Reciptionist
		[HttpGet]
		public async Task<IActionResult> EditReciptionist(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = await _client.GetAsync(_client.BaseAddress +
					$"/Reciptionist/GetReciptionistById?id={id}");
				if (response.IsSuccessStatusCode)
				{
					string data = response.Content.ReadAsStringAsync().Result;
					var reciptionist = JsonConvert.DeserializeObject<ReciptionistVM>(data);
					return View(reciptionist);
				}
				else
				{
					return RedirectToAction("Index");
				}

			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		[HttpPost]
		public async Task<IActionResult> EditReciptionist(int id, ReciptionistVM model)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				string data = JsonConvert.SerializeObject(model);
				StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
				HttpResponseMessage response = await _client.PutAsync(_client.BaseAddress +
					$"/Reciptionist/EditReciptionist?id={id}", content);
				if (response.IsSuccessStatusCode)
				{
					TempData["successMessage"] = "Reciptionist Details Updated.";
					_toastNotification.AddSuccessToastMessage("Reciptionist Updated successfully");
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
			return View();
		}

		//Delete Reciptionist 
		public async Task<IActionResult> DeleteReciptionist(int id)
		{
			try
			{
				var accessToken = HttpContext.Session.GetString("JWToken");
				_client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
				HttpResponseMessage response = await _client.DeleteAsync(_client.BaseAddress +
					$"/Reciptionist/{id}");
				if (response.IsSuccessStatusCode)
				{
					TempData["successMessage"] = "Reciptionist Details Deleted.";
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
			return View();
		}
	}
}

HeartDiseasePrediction/Views/Reciptionist/EditReciptionist.cshtml
@model HeartDiseasePrediction.ViewModel.ReciptionistVM

@{
    ViewData["Title"] = "Reciptionist Update Page";
}

<section class="book_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-action="EditReciptionist" enctype="multipart/form-data">
                    <h4>
                        Update <span>Reciptionist</span>
                    </h4>
                    <div class="form-row ">
                        <div class="form-group col-lg-6">
                            <label asp-for="@Model.FullName" class="control-label"></label>
                            <input asp-for="@Model.FullName" type="text" class="form-control" id="inputFullName">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.FirstName" class="control-label"></label>
                            <input asp-for="@Model.FirstName" type="text" class="form-control" id="inputFirstname">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.LastName" class="control-label"></label>
                            <input asp-for="@Model.LastName" type="text" class="form-control" id="inputLastName">
                        </div>
                    </div>
                    <div class="form-row ">
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.PhoneNumber" class="control-label"></label>
                            <input asp-for="@Model.PhoneNumber" type="number" class="form-control" id="inputPhone">
                        </div>
                        @*<div class="form-group col-lg-3">
                            <label asp-for="@Model.Address" class="control-label"></label>
                            <input asp-for="@Model.Address" type="text" class="form-control" id="inputAddress">
                        </div>*@
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.Gender"></label>
                            <select asp-for="@Model.Gender" class="form-control wide" id="inputGender" asp-items="Html.GetEnumSelectList<Gender>()">
                                <option value="NoSelected ">--Please Select Gender-- </option>
                            </select>
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.BirthDate"></label>
                            <input asp-for="@Model.BirthDate" type="datetime" class="form-control">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.Email"></label>
                            <input asp-for="@Model.Email" type="text" class="form-control" id="Email">
                        </div>
                        <div class="form-group col-lg-4" hidden>
                            <label asp-for="@Model.Id"></label>
                            <input asp-for="@Model.Id" type="text" class="form-control" id="Id">
                        </div>
                        <div class="">
                            <div class="form-group col-lg-5">
                                <img id="profilePicture" class="border-info rounded-circle" style="max-width:150px" />
                                <label asp-for="ProfileImg" class="w-100"></label>
                                <input accept="image/*" asp-for="ImageFile"
                                       onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                                <span asp-validation-for="ImageFile" class="text-danger"></span>
                                @*@if (@Model.ProfileImg != null)
                                {
                                    <img id="profilePicture" alt="profile" class="profile-picture" style="height:255px; width:255px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(Model.ProfileImg))" />
                                }
                                else
                                {
                                    <img id="profilePicture" alt="profile" class="profile-picture" style="height:255px; width:255px; object-fit:cover" src="~/images/avater.png" />
                                }
                                <div class="custom-file mt-2">
                                    <input type="file"
                                           accept="image/*"
                                           asp-for="@Model.ProfileImg"
                                           class="custom-file-input"
                                           onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                                    <label class="custom-file-label" asp-for="@Model.ProfileImg">Choose picture...</label>
                                    <span asp-validation-for="@Model.ProfileImg" class="text-danger"></span>
                                </div>*@
                            </div>
                        </div>
                        @*<div class="form-group col-lg-4">
                            <label asp-for="@Model.Password"></label>
                            <input asp-for="@Model.Password" type="password" class="form-control" id="Password" disabled>
                        </div>*@
                    </div>
                    <div class="btn-box">
                        <button type="submit" class="btn ">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

@*@section Scripts{
    <script>
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}*@

HeartDiseasePrediction/Views/Reciptionist/Index.cshtml
@model IEnumerable<HeartDiseasePrediction.Models.ReciptionistViewModel>

@{
    ViewData["Title"] = "Reciptionists List Page";
}

<div class="container mt-4" style="margin:40px">
	<div class="row">
		<div class="col-md-12 offset-md-0">
			<div class="main-body">
				<nav aria-label="breadcrumb" class="main-breadcrumb ">
					<ol class="breadcrumb">
						<li class="breadcrumb-item">Reciptionists</li>
						<li class="breadcrumb-item">List</li>
						<li class="breadcrumb-item active" aria-current="page">List of Reciptionists</li>
					</ol>
				</nav>
			</div>
			<div class="form-inline my-2 my-lg-0 d-flex">
				<a asp-controller="Account" asp-action="RegisterOfReciptionist" class="btn btn-success">
					<i class="fa fa-plus-circle"></i> Add New
				</a>
			</div>
			@if (!Model.Any())
			{
				<div class="alert alert-warning" role="alert">
					No Reciptionists Found
				</div>
			}
			else
			{
				<div class="form-inline my-2 my-lg-0 d-flex" style="padding-left:68%">
					@using (Html.BeginForm("Index", "Reciptionist", FormMethod.Post))
					{
						@Html.TextBox("search",null,new{@class="form-control",placeholder="Search here...",style="margin:5px 0px 5px 5px"})
						<button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> Search</button>
					}
				</div>
				<table class="table table-hover table-responsive table-striped">
					<thead>
						<tr class="text-center bg-dark text-light">
							<th>#</th>
							<th>Email</th>
							<th>Full Name</th>
							<th>Gender</th>
							<th>Age</th>
							<th>Phone</th>
							<th>	
							</th>
							@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
						{
						<th>Action</th>
						}*@

						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr>
								@*<td class="align-middle text-center">
						<img class="rounded-circle" src="@item.ProfileImg" alt="@item.FullName" style="max-width:150px">
						</td>*@
								<td class="align-middle text-center">
									@item.Id
								</td>
								<td class="align-middle text-center">
									@item.User.Email
								</td>
								<td class="align-middle text-center">
									@item.User.FullName
								</td>
								<td class="align-middle text-center">
									@item.User.Gender
								</td>
								<td class="align-middle text-center">
									@item.User.Age
								</td>
								<td class="align-middle text-center">
									@item.User.PhoneNumber
								</td>
								<td class="align-middle text-center">
									<a class="btn btn-outline-primary" asp-controller="Reciptionist" asp-action="EditReciptionist" asp-route-id="@item.Id"><i class="fa fa-pencil-square"></i> Edit</a> |
									<a class="btn btn-outline-info" asp-controller="Reciptionist" asp-action="ReciptionistDetails" asp-route-id="@item.Id"><i class="fa fa-eye"></i> Details</a> |
									<a class="btn btn-outline-danger " asp-controller="Reciptionist" asp-action="DeleteReciptionist" asp-route-id="@item.Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
								</td>
								@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
						{
						<td class="align-middle text-center">
						<a class="btn btn-outline-primary" asp-controller="Reciptionist" asp-action="Edit" asp-route-id="Id"><i class="fa fa-pencil-square"></i> Edit</a> |
						<a class="btn btn-outline-info" asp-controller="Reciptionist" asp-action="Details" asp-route-id="Id"><i class="fa fa-eye"></i> Details</a> |
						<a class="btn btn-outline-danger " asp-controller="Reciptionist" asp-action="Delete" asp-route-id="Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
						</td>
						}*@
							</tr>
						}
					</tbody>
				</table>
			}
		</div>
	</div>
</div>
@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
	<div style="position:fixed; right:25px; bottom:65px;" class="text-white">
		<a asp-controller="Actor" asp-action="Create" class="btn btn-success">
			<i class="bi bi-plus-circle"></i> Add New
		</a>
	</div>
}*@

<script>
	function ConfirmDelete() {
		document.getElementById("");
		var accept = confirm("Are You Sure to delete this actor?");
		if (accept == false) {
			event.preventDefault();
		}
	}
</script>

HeartDiseasePrediction/Views/Reciptionist/ReciptionistDetails.cshtml
@model HeartDiseasePrediction.ViewModel.ReciptionistVM

@{
    ViewData["Title"] = "Patient Profile Page";
}

<style type="text/css">
    body {
        margin-top: 20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;
    }

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

        .gutters-sm > .col, .gutters-sm > [class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }

</style>

<div class="container">
    <div class="main-body">
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Reciptionist</li>
                <li class="breadcrumb-item">Details</li>
                <li class="breadcrumb-item active" aria-current="page">Reciptionist Profile</li>
            </ol>
        </nav>
    </div>
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><strong>@Model.FirstName</strong> <strong>@Model.LastName</strong></h4>
                            <p class="text-secondary mb-1">Reciptionist</p>
                            <p class="text-muted font-size-sm">@Model.Email</p>
                            <a class="btn btn-primary" asp-controller="Reciptionist" asp-action="EditReciptionist" asp-route-id="@Model.Id"><i class="fa fa-pencil-square"></i>  Edit</a>
                            <button class="btn btn-danger" asp-controller="Reciptionist" asp-action="DeleteReciptionist" asp-route-id="@Model.Id" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.FullName
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Email
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.PhoneNumber
                        </div>
                    </div>       
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Birth Date</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.BirthDate
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Age</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Age
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Gender
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    function ConfirmDelete() {
        document.getElementById("");
        var accept = confirm("Are You Sure to delete this actor?");
        if (accept == false) {
            event.preventDefault();
        }
    }
</script>